// Shared IPC contract between the Electron main process and the renderer.
// Everything crossing the bridge must be structured-clone friendly (plain data).

export type PermissionMode = 'default' | 'acceptEdits' | 'bypassPermissions' | 'plan' | 'dontAsk' | 'auto'
export type EffortLevel = 'low' | 'medium' | 'high' | 'xhigh' | 'max'

/** Persisted metadata about a session managed by ClaudeGUI. */
export interface SessionRecord {
  /** Stable ClaudeGUI id (UUID). */
  id: string
  /** Claude Code session id (normally equal to `id`). */
  claudeSessionId: string
  title: string
  /** True while the title is auto-generated by Claude Code. */
  autoTitle?: boolean
  cwd: string
  model?: string
  permissionMode: PermissionMode
  effort?: EffortLevel
  createdAt: number
  lastActiveAt: number
  pinned?: boolean
  archived?: boolean
  source: 'gui' | 'cli-import'
  /** Set when a /clear produced a new conversation id inside the same process. */
  conversationId?: string
  /** Estimated USD cost accumulated across all processes of this session. */
  totalCostUsd?: number
}

export type SessionStatus = 'stopped' | 'starting' | 'idle' | 'running' | 'requires_action' | 'error'

export interface PendingPermission {
  requestId: string
  toolUseId: string
  toolName: string
  input: Record<string, unknown>
  suggestions?: unknown[]
  title?: string
  description?: string
  displayName?: string
  decisionReason?: string
  blockedPath?: string
  agentId?: string
  createdAt: number
}

export interface BackgroundTaskView {
  taskId: string
  taskType: string
  description: string
  ambient?: boolean
  status?: 'pending' | 'running' | 'completed' | 'failed' | 'killed' | 'paused' | 'stopped'
  toolUseId?: string
  summary?: string
  lastToolName?: string
  usage?: { total_tokens: number; tool_uses: number; duration_ms: number }
  startedAt?: number
}

export interface ActiveToolView {
  toolUseId: string
  toolName: string
  elapsedSeconds: number
  parentToolUseId: string | null
}

export interface TurnStats {
  costUsd: number
  durationMs: number
  numTurns: number
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
  cacheCreationTokens: number
  isError: boolean
  endedAt: number
}

export interface RateLimitView {
  status: 'allowed' | 'allowed_warning' | 'rejected'
  rateLimitType?: string
  utilization?: number
  resetsAt?: number
}

export interface SlashCommandView {
  name: string
  description: string
  argumentHint: string
  aliases?: string[]
}

export interface ModelInfoView {
  value: string
  displayName: string
  description: string
  supportedEffortLevels?: EffortLevel[]
}

export interface SessionLiveState {
  id: string
  status: SessionStatus
  processAlive: boolean
  model?: string
  permissionMode?: PermissionMode
  effort?: EffortLevel | null
  claudeVersion?: string
  cwd?: string
  activity?: 'compacting' | 'requesting' | null
  pendingPermissions: PendingPermission[]
  backgroundTasks: BackgroundTaskView[]
  activeTools: ActiveToolView[]
  lastTurn?: TurnStats
  totalCostUsd: number
  contextTokens?: number
  contextWindow?: number
  rateLimit?: RateLimitView
  unread: number
  lastActivityAt: number
  lastPreview?: string
  error?: string
  slashCommands?: SlashCommandView[]
  models?: ModelInfoView[]
  queuedCount: number
}

// ---------------------------------------------------------------------------
// Chat transcript model
// ---------------------------------------------------------------------------

export interface ImageAttachment {
  mediaType: string
  data: string // base64
  name?: string
}

export interface TextBlockView {
  type: 'text'
  text: string
}
export interface ThinkingBlockView {
  type: 'thinking'
  text: string
}
export interface ToolResultView {
  content: string
  images?: ImageAttachment[]
  isError: boolean
  structured?: unknown
  receivedAt: number
}
export interface ToolUseBlockView {
  type: 'tool_use'
  id: string
  name: string
  input: Record<string, unknown>
  /** Raw JSON accumulated while streaming; cleared once parsed. */
  partialJson?: string
  status: 'streaming' | 'pending' | 'running' | 'done' | 'error' | 'denied'
  startedAt: number
  result?: ToolResultView
  /** Messages produced inside a subagent started by this tool call. */
  children?: ChatMessage[]
  task?: {
    taskId: string
    description?: string
    subagentType?: string
    status?: BackgroundTaskView['status']
    summary?: string
    lastToolName?: string
    usage?: BackgroundTaskView['usage']
    isBackgrounded?: boolean
    outputFile?: string
  }
}
export type AssistantBlockView = TextBlockView | ThinkingBlockView | ToolUseBlockView

export interface UserChatMessage {
  kind: 'user'
  id: string
  ts: number
  text: string
  images?: ImageAttachment[]
  /** True for messages the CLI generated itself (task notifications, hook output, etc.). */
  synthetic?: boolean
  parentToolUseId: string | null
}
export interface AssistantChatMessage {
  kind: 'assistant'
  id: string
  ts: number
  model?: string
  blocks: AssistantBlockView[]
  streaming: boolean
  aborted?: boolean
  error?: string
  stopReason?: string | null
  parentToolUseId: string | null
  subagentType?: string
}
export interface SystemChatMessage {
  kind: 'system'
  id: string
  ts: number
  subtype: string
  level: 'info' | 'notice' | 'suggestion' | 'warning' | 'error'
  text: string
  data?: Record<string, unknown>
}
export interface ResultChatMessage {
  kind: 'result'
  id: string
  ts: number
  stats: TurnStats
  errorText?: string
}
export type ChatMessage = UserChatMessage | AssistantChatMessage | SystemChatMessage | ResultChatMessage

// ---------------------------------------------------------------------------
// Events main -> renderer
// ---------------------------------------------------------------------------

export type SessionEvent =
  | { type: 'state'; state: SessionLiveState }
  | { type: 'record'; record: SessionRecord }
  | { type: 'record-removed'; id: string }
  | { type: 'message'; sessionId: string; message: ChatMessage }
  | { type: 'messages-reset'; sessionId: string; messages: ChatMessage[] }
  | { type: 'message-removed'; sessionId: string; messageId: string }
  | { type: 'focus'; sessionId: string }

export interface PermissionDecision {
  behavior: 'allow' | 'deny'
  updatedInput?: Record<string, unknown>
  alwaysAllow?: boolean
  message?: string
  interrupt?: boolean
}

// ---------------------------------------------------------------------------
// Filesystem
// ---------------------------------------------------------------------------

export interface FsEntry {
  name: string
  path: string
  isDir: boolean
  isSymlink: boolean
  size: number
  mtime: number
  ext: string
}

export interface FileContent {
  path: string
  kind: 'text' | 'image' | 'binary' | 'too-large' | 'missing'
  text?: string
  base64?: string
  mimeType?: string
  size: number
  mtime: number
  language?: string
  truncated?: boolean
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

export interface AppSettings {
  /** Path to a claude binary; empty = SDK-bundled binary. */
  claudeExecutable: string
  /** Command used for "open in editor"; supports {path} and {line} placeholders. */
  editorCommand: string
  defaultModel: string
  defaultPermissionMode: PermissionMode
  defaultEffort: EffortLevel | ''
  notifications: boolean
  showHiddenFiles: boolean
  fontSize: number
  recentDirectories: string[]
  sendWithEnter: boolean
  /** Extra KEY=VALUE lines applied to every Claude process (e.g. proxies). */
  extraEnv: string
}

export interface CliSessionSummary {
  sessionId: string
  summary: string
  lastModified: number
  createdAt?: number
  cwd?: string
  firstPrompt?: string
  customTitle?: string
  fileSize?: number
  gitBranch?: string
  alreadyImported: boolean
}

export interface AppInfo {
  version: string
  electron: string
  node: string
  sdkVersion: string
  userDataPath: string
  claudeExecutable: string
  homeDir: string
}
