// Shared IPC contract between the Electron main process and the renderer.
// Everything crossing the bridge must be structured-clone friendly (plain data).

export type PermissionMode = 'default' | 'acceptEdits' | 'bypassPermissions' | 'plan' | 'dontAsk' | 'auto'
export type EffortLevel = 'low' | 'medium' | 'high' | 'xhigh' | 'max'

/** Persisted metadata about a session managed by ClaudeGUI. */
export interface SessionRecord {
  /** Stable ClaudeGUI id (UUID). */
  id: string
  /** Claude Code session id (normally equal to `id`). */
  claudeSessionId: string
  title: string
  /** True while the title is auto-generated by Claude Code. */
  autoTitle?: boolean
  cwd: string
  model?: string
  permissionMode: PermissionMode
  effort?: EffortLevel
  createdAt: number
  lastActiveAt: number
  /** When you last sent a prompt (not when Claude last answered); drives the "recent" order. */
  lastPromptAt?: number
  /** Model the last process reported at start (shown while the session is not running). */
  lastModel?: string
  pinned?: boolean
  archived?: boolean
  source: 'gui' | 'cli-import'
  /** Set when a /clear produced a new conversation id inside the same process. */
  conversationId?: string
  /** Estimated USD cost accumulated across all processes of this session. */
  totalCostUsd?: number
  /** User-defined group (see SessionGroup); undefined = ungrouped. */
  groupId?: string
  /** Manual position inside its group (lower first); only drag & drop changes it. */
  order?: number
}

/** User-defined category of sessions ("Papers", "Utilities", "Tasks", …). */
export interface SessionGroup {
  id: string
  name: string
  /** Position among groups (lower first). */
  order: number
  collapsed?: boolean
  /** Group colour as #rrggbb (assigned automatically when the group is created; user-changeable). */
  color?: string
}

/** Where to drop a session when moving it (drag & drop / "Move to group"). */
export interface SessionMove {
  groupId?: string
  /** Insert before this session id; omitted = append at the end of the group. */
  beforeId?: string
}

export type SessionStatus = 'stopped' | 'starting' | 'idle' | 'running' | 'requires_action' | 'error'

export interface PendingPermission {
  requestId: string
  toolUseId: string
  toolName: string
  input: Record<string, unknown>
  suggestions?: unknown[]
  title?: string
  description?: string
  displayName?: string
  decisionReason?: string
  blockedPath?: string
  agentId?: string
  createdAt: number
}

export interface BackgroundTaskView {
  taskId: string
  taskType: string
  description: string
  ambient?: boolean
  status?: 'pending' | 'running' | 'completed' | 'failed' | 'killed' | 'paused' | 'stopped'
  toolUseId?: string
  summary?: string
  lastToolName?: string
  usage?: { total_tokens: number; tool_uses: number; duration_ms: number }
  startedAt?: number
}

export interface ActiveToolView {
  toolUseId: string
  toolName: string
  elapsedSeconds: number
  parentToolUseId: string | null
}

export interface TurnStats {
  costUsd: number
  durationMs: number
  numTurns: number
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
  cacheCreationTokens: number
  isError: boolean
  endedAt: number
}

export interface RateLimitView {
  status: 'allowed' | 'allowed_warning' | 'rejected'
  rateLimitType?: string
  utilization?: number
  resetsAt?: number
}

export interface SlashCommandView {
  name: string
  description: string
  argumentHint: string
  aliases?: string[]
}

export interface ModelInfoView {
  value: string
  displayName: string
  description: string
  supportedEffortLevels?: EffortLevel[]
}

export interface SessionLiveState {
  id: string
  status: SessionStatus
  processAlive: boolean
  model?: string
  permissionMode?: PermissionMode
  effort?: EffortLevel | null
  claudeVersion?: string
  cwd?: string
  activity?: 'compacting' | 'requesting' | null
  pendingPermissions: PendingPermission[]
  backgroundTasks: BackgroundTaskView[]
  activeTools: ActiveToolView[]
  lastTurn?: TurnStats
  totalCostUsd: number
  contextTokens?: number
  contextWindow?: number
  contextUsage?: ContextUsageView
  rateLimit?: RateLimitView
  unread: number
  lastActivityAt: number
  lastPreview?: string
  error?: string
  /** The working directory does not exist (renamed or deleted); the process cannot start. */
  cwdMissing?: boolean
  /** When the current process was started (epoch ms). */
  processStartedAt?: number
  slashCommands?: SlashCommandView[]
  models?: ModelInfoView[]
  queuedCount: number
  /** Ids of the prompts Claude Code has not taken off its queue yet, oldest first. */
  queuedIds: string[]
  /**
   * What Claude Code has done with each prompt this app sent, as far as it has said so itself.
   * Only prompts whose turn has not finished appear here; a finished one is dropped and the chat
   * reads its state from the transcript instead.
   */
  promptDelivery: Record<string, PromptDelivery>
  /** Shell commands typed after "!" that are still running, by the id of their row in the chat. */
  runningShellIds?: string[]
  /** When this chat last failed because Claude Code's login was not accepted (cleared by the next real answer). */
  authFailedAt?: number
  /** What Claude Code said when that happened. */
  authError?: string
}

/** A prompt is waiting in Claude Code's queue, or is being answered by the turn running now. */
export type PromptDelivery = 'queued' | 'working'

// ---------------------------------------------------------------------------
// Chat transcript model
// ---------------------------------------------------------------------------

export interface ImageAttachment {
  mediaType: string
  data: string // base64
  name?: string
}

export interface TextBlockView {
  type: 'text'
  text: string
}
export interface ThinkingBlockView {
  type: 'thinking'
  text: string
}
export interface ToolResultView {
  content: string
  images?: ImageAttachment[]
  isError: boolean
  structured?: unknown
  receivedAt: number
}
export interface ToolUseBlockView {
  type: 'tool_use'
  id: string
  name: string
  input: Record<string, unknown>
  /** Raw JSON accumulated while streaming; cleared once parsed. */
  partialJson?: string
  status: 'streaming' | 'pending' | 'running' | 'done' | 'error' | 'denied'
  startedAt: number
  result?: ToolResultView
  /** Messages produced inside a subagent started by this tool call. */
  children?: ChatMessage[]
  task?: {
    taskId: string
    description?: string
    subagentType?: string
    status?: BackgroundTaskView['status']
    summary?: string
    lastToolName?: string
    usage?: BackgroundTaskView['usage']
    isBackgrounded?: boolean
    outputFile?: string
  }
}
export type AssistantBlockView = TextBlockView | ThinkingBlockView | ToolUseBlockView

export interface UserChatMessage {
  kind: 'user'
  id: string
  ts: number
  text: string
  images?: ImageAttachment[]
  /** True for messages the CLI generated itself (task notifications, hook output, etc.). */
  synthetic?: boolean
  parentToolUseId: string | null
}
export interface AssistantChatMessage {
  kind: 'assistant'
  id: string
  /**
   * UUID of this message in Claude Code's own transcript chain (the id above is the API message
   * id). Needed as the point a rewound conversation is resumed from.
   */
  chainUuid?: string
  ts: number
  model?: string
  blocks: AssistantBlockView[]
  streaming: boolean
  aborted?: boolean
  error?: string
  stopReason?: string | null
  parentToolUseId: string | null
  subagentType?: string
}
export interface SystemChatMessage {
  kind: 'system'
  id: string
  ts: number
  subtype: string
  level: 'info' | 'notice' | 'suggestion' | 'warning' | 'error'
  text: string
  data?: Record<string, unknown>
}
export interface ResultChatMessage {
  kind: 'result'
  id: string
  ts: number
  stats: TurnStats
  errorText?: string
}
export type ChatMessage = UserChatMessage | AssistantChatMessage | SystemChatMessage | ResultChatMessage

/** The outcome of taking a still-waiting prompt back out of Claude Code's queue. */
export interface QueuedPromptTakeBack {
  /** False when Claude Code had already taken the prompt, so it is being answered after all. */
  cancelled: boolean
  /** The prompt text, for the input box. */
  text: string
  images?: ImageAttachment[]
}

/** What a rewind to one of your prompts would do (asked before it is carried out). */
export interface RewindPreview {
  /** The text of that prompt; it goes back into the input box so you can edit and send it again. */
  text: string
  /** False when the conversation cannot be cut back to this point (see reason). */
  canRewind: boolean
  reason?: string
  /** Whether the files Claude changed since then can be put back, and how much would change. */
  files: {
    available: boolean
    reason?: string
    changed: number
    insertions: number
    deletions: number
    paths: string[]
  }
}

export interface RewindResult {
  /** The prompt text that was cut away, for the input box. */
  text: string
  /** Number of files put back (0 when only the conversation was rewound). */
  filesRestored: number
  /** Files that were tracked but could not be restored safely. */
  filesSkipped: number
  /** Whether Claude Code was started again at the fork point (only when it was running before). */
  restarted: boolean
}

// ---------------------------------------------------------------------------
// Events main -> renderer
// ---------------------------------------------------------------------------

export type SessionEvent =
  | { type: 'state'; state: SessionLiveState }
  | { type: 'record'; record: SessionRecord }
  | { type: 'groups'; groups: SessionGroup[] }
  | { type: 'record-removed'; id: string }
  | { type: 'message'; sessionId: string; message: ChatMessage }
  | { type: 'messages-reset'; sessionId: string; messages: ChatMessage[] }
  | { type: 'message-removed'; sessionId: string; messageId: string }
  | { type: 'focus'; sessionId: string }

export interface PermissionDecision {
  behavior: 'allow' | 'deny'
  updatedInput?: Record<string, unknown>
  alwaysAllow?: boolean
  message?: string
  interrupt?: boolean
}

// ---------------------------------------------------------------------------
// Filesystem
// ---------------------------------------------------------------------------

export interface FsEntry {
  name: string
  path: string
  isDir: boolean
  isSymlink: boolean
  size: number
  mtime: number
  ext: string
}

export interface FileContent {
  path: string
  kind: 'text' | 'image' | 'binary' | 'too-large' | 'missing'
  text?: string
  base64?: string
  mimeType?: string
  size: number
  mtime: number
  language?: string
  truncated?: boolean
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

export type ThemeMode = 'system' | 'light' | 'dark'
export type AccentColor = 'system' | 'blue' | 'purple' | 'pink' | 'red' | 'orange' | 'yellow' | 'green' | 'graphite' | 'claude'
export type Density = 'comfortable' | 'compact'

/** Order of the file tree in the folder panel. */
export type FileSort = 'name' | 'name-desc' | 'modified' | 'size' | 'type'
export type ThinkingDisplay = 'collapsed' | 'expanded' | 'hidden'
export type DoubleClickAction = 'system' | 'editor' | 'viewer'
/**
 * Where a plain click on a file goes: 'system' hands every file to the app Finder would use;
 * 'viewer-text' shows text and images in the built-in viewer and hands the rest to their app;
 * 'viewer' shows everything the viewer can show in the viewer.
 */
export type OpenFilesWith = 'system' | 'viewer-text' | 'viewer'
export type ResumeOnLaunch = 'none' | 'active' | 'pinned' | 'all'

/** Sidebar layout: sessions grouped by their user-defined group, or a flat pinned / recent list. */
export type SidebarView = 'groups' | 'recent'
/** Session order inside a group or list. */
export type SidebarSort = 'lastPrompt' | 'manual'

export interface AppSettings {
  // ---- Claude
  /** Path to a claude binary; empty = SDK-bundled binary. */
  claudeExecutable: string
  defaultModel: string
  defaultPermissionMode: PermissionMode
  defaultEffort: EffortLevel | ''
  /** Extra KEY=VALUE lines applied to every Claude process (e.g. proxies). */
  extraEnv: string
  /** Maximum agent turns per message; 0 = unlimited. */
  maxTurns: number
  /** Maximum thinking tokens; 0 = model default. */
  maxThinkingTokens: number
  /** Tools that never prompt (comma or newline separated, e.g. "Read,Grep,Bash(git *)"). */
  allowedTools: string
  /** Tools Claude may not use at all. */
  disallowedTools: string
  useProjectSettings: boolean
  useLocalSettings: boolean
  /**
   * Keep a copy of every file before Claude changes it, so a chat can be rewound to an earlier
   * prompt and the files put back as they were. Costs disk space in ~/.claude.
   */
  fileCheckpointing: boolean
  /** Let Claude Code name new sessions automatically. */
  autoTitle: boolean

  // ---- General
  notifications: boolean
  notifyOnTurnFinished: boolean
  notifyOnPermission: boolean
  notifyOnError: boolean
  notificationSound: boolean
  dockBadge: boolean
  resumeOnLaunch: ResumeOnLaunch
  confirmQuit: boolean
  /** Pre-filled working directory for new sessions. */
  defaultCwd: string
  sendWithEnter: boolean
  recentDirectories: string[]

  // ---- Appearance
  theme: ThemeMode
  accent: AccentColor
  fontSize: number
  uiFont: string
  codeFont: string
  codeFontSize: number
  density: Density
  showTimestamps: boolean
  thinkingDisplay: ThinkingDisplay
  toolCardsExpanded: boolean
  /** Order of the files in the folder panel (folders always first). */
  fileSort: FileSort
  chatMaxWidth: number
  groupSessionsByFolder: boolean
  translucentSidebar: boolean
  /** One-line statistics bar (n working, n waiting, …) above the chat. */
  showStatusBoard: boolean
  /** Sidebar layout: by group, or a flat pinned / recent list. */
  sidebarView: SidebarView
  /** Order of sessions inside a group / list: by your last prompt, or manual (drag & drop). */
  sidebarSort: SidebarSort
  /** Hover explanations on buttons and indicators. */
  showTooltips: boolean

  // ---- Files
  /** Command used for "open in editor"; supports {path} and {line} placeholders. */
  editorCommand: string
  showHiddenFiles: boolean
  /** Names hidden from the file tree (comma separated, e.g. node_modules,.git). */
  excludePatterns: string
  /** What a click on a file does (chat links, file tree, Git panel); the viewer stays in the right-click menu. */
  openFilesWith: OpenFilesWith
  doubleClickAction: DoubleClickAction
  autoRevealEditedFiles: boolean
  maxPreviewKB: number
  showFileSizes: boolean

  // ---- Git
  gitEnabled: boolean
  gitShowStatusInTree: boolean
  gitAutoRefreshSeconds: number
  gitAutoFetchMinutes: number
  gitPushAfterCommit: boolean
  gitSignOff: boolean
  gitCommitTemplate: string

  // ---- Usage
  usageRefreshMinutes: number
  usageWarnPercent: number
  showUsageStatus: boolean
  showContextInSidebar: boolean
  showTaskCountsInSidebar: boolean

  // ---- Updates
  /** Git repository (URL or local path) whose tags are the released versions. */
  updateRepo: string
  /** Restart into the new version automatically once it has been built. */
  updateAutoRestart: boolean
  /** Folder for the update source checkout and build output (empty = ~/Library/Caches/ClaudeGUI/update). */
  updateWorkDir: string

  // ---- Advanced
  toolResultMaxChars: number
  debugServer: boolean
  debugPort: number
}

export interface ThemeInfo {
  systemDark: boolean
  /** macOS accent colour as #rrggbb. */
  accent: string
}

// ---------------------------------------------------------------------------
// Plan usage limits (claude.ai rate-limit windows)
// ---------------------------------------------------------------------------

export type UsageSeverity = 'normal' | 'warning' | 'critical' | 'locked' | 'unknown'

export interface UsageWindow {
  key: string
  label: string
  group: 'session' | 'weekly' | 'model' | 'monthly' | 'other'
  /** 0-100, or null when the server did not report it. */
  percent: number | null
  severity: UsageSeverity
  /** Epoch ms when the window resets. */
  resetsAt?: number
  isActive?: boolean
  detail?: string
  /** Epoch ms of the last update for this window. */
  updatedAt: number
}

export interface UsageSnapshot {
  /** Epoch ms of the last explicit check (0 = never). */
  fetchedAt: number
  source: 'endpoint' | 'session' | 'event' | 'none'
  subscription?: string | null
  windows: UsageWindow[]
  error?: string
  nextCheckAt?: number
  checking?: boolean
}

// ---------------------------------------------------------------------------
// Claude Code login
// ---------------------------------------------------------------------------

/**
 * Whether Claude Code can authenticate, as far as the app can tell without touching the tokens:
 * the login it stored (macOS Keychain or ~/.claude/.credentials.json) and `claude auth status`.
 */
export interface AuthState {
  /** signed-in: a claude.ai login is stored · signed-out: none, chats cannot run · api-key: another way of signing in */
  status: 'unknown' | 'signed-in' | 'signed-out' | 'api-key'
  checkedAt: number
  /** Since when the status has been what it is (epoch ms); chat failures from before do not count. */
  statusSince?: number
  subscription?: string
  /** When Claude Code's stored refresh token stops being accepted (epoch ms), if it recorded that. */
  loginEndsAt?: number
  /** A sign-in started from the app: the browser page to finish it on, and how it went. */
  signIn?: { phase: 'starting' | 'waiting' | 'done' | 'failed' | 'cancelled'; url?: string; message?: string }
}

// ---------------------------------------------------------------------------
// Context usage of a session
// ---------------------------------------------------------------------------

export interface ContextUsageView {
  totalTokens: number
  /** The window the percentage is measured against (auto-compact window). */
  maxTokens: number
  percentage: number
  model?: string
  categories: { name: string; tokens: number; kind?: string; color?: string }[]
  checkedAt: number
}

// ---------------------------------------------------------------------------
// Git
// ---------------------------------------------------------------------------

export type GitFileState = 'modified' | 'added' | 'deleted' | 'renamed' | 'copied' | 'typechange' | 'conflicted' | 'untracked' | 'ignored'

export interface GitFileStatus {
  /** Repo-relative path (directories end with '/'). */
  path: string
  absPath: string
  origPath?: string
  /** Staged (index) change. */
  index: GitFileState | null
  /** Unstaged (working tree) change. */
  worktree: GitFileState | null
  isDir: boolean
}

export interface GitRepoInfo {
  isRepo: boolean
  gitAvailable: boolean
  ghAvailable: boolean
  root?: string
  branch?: string
  detached?: boolean
  upstream?: string
  ahead?: number
  behind?: number
  remoteName?: string
  remoteUrl?: string
  remoteWebUrl?: string
  head?: { hash: string; subject: string; time: number }
  userName?: string
  userEmail?: string
  stashCount?: number
  hasCommits?: boolean
}

export interface GitStatusResult {
  info: GitRepoInfo
  files: GitFileStatus[]
  truncated?: boolean
  checkedAt: number
}

export interface GitCommitInfo {
  hash: string
  shortHash: string
  subject: string
  author: string
  time: number
  refs?: string
}

export interface GitDiffResult {
  path: string
  before: string
  after: string
  beforeLabel: string
  afterLabel: string
  binary: boolean
  tooLarge?: boolean
}

export interface GitBranchInfo {
  name: string
  current: boolean
  upstream?: string
}

export interface FileProbe {
  kind: 'text' | 'image' | 'binary' | 'too-large' | 'missing' | 'dir' | 'bundle'
  size: number
  ext: string
}

export interface CliSessionSummary {
  sessionId: string
  summary: string
  lastModified: number
  createdAt?: number
  cwd?: string
  firstPrompt?: string
  customTitle?: string
  fileSize?: number
  gitBranch?: string
  alreadyImported: boolean
}

export interface AppInfo {
  version: string
  platform: string
  electron: string
  node: string
  sdkVersion: string
  userDataPath: string
  claudeExecutable: string
  homeDir: string
  /** True when running from a built .app bundle (updates are only possible then). */
  packaged: boolean
  bundlePath?: string
  logFile: string
}

// ---------------------------------------------------------------------------
// Session host (detached process that owns the Claude processes) and updates
// ---------------------------------------------------------------------------

/** Structured /usage as reported by the CLI's experimental SDK method. */
export interface SdkUsage {
  subscription_type?: string | null
  rate_limits_available?: boolean
  rate_limits?: Record<string, unknown> | null
}

export interface HostStatus {
  connected: boolean
  pid?: number
  /** App version that started the host process. */
  version?: string
  protocol?: number
  startedAt?: number
  socketPath?: string
  logFile?: string
  aliveSessions: number
  /** True when the host was started by a different app version than the one running now. */
  stale: boolean
  /** 'attached' when this app instance found the host already running. */
  origin?: 'attached' | 'spawned'
}

export type UpdateStatus = 'idle' | 'unsupported' | 'checking' | 'up-to-date' | 'available' | 'building' | 'ready' | 'applying' | 'error'

export interface UpdateState {
  status: UpdateStatus
  currentVersion: string
  latestVersion?: string
  /** Changelog section of the latest version, when available. */
  notes?: string
  checkedAt?: number
  /** Human-readable current step while building. */
  step?: string
  stepIndex?: number
  stepCount?: number
  /** Tail of the build log. */
  log: string[]
  error?: string
  bundlePath?: string
  workDir?: string
  logFile?: string
  startedAt?: number
  finishedAt?: number
  autoRestart: boolean
}

export interface StartupNotice {
  kind: 'info' | 'error' | 'success'
  text: string
}

// ---------------------------------------------------------------------------
// Working-directory info and macOS privacy permissions
// ---------------------------------------------------------------------------

export interface DirInfo {
  path: string
  exists: boolean
  /** Total size in bytes (du -sk), undefined while unknown or when the folder is missing. */
  bytes?: number
  /** Number of files (find -type f), undefined when not counted. */
  files?: number
  checkedAt: number
  /** True when the size computation was cut short. */
  partial?: boolean
}

export type PermissionState = 'granted' | 'denied' | 'not-determined' | 'restricted' | 'unknown' | 'unsupported'

export interface PermissionInfo {
  key: string
  label: string
  description: string
  state: PermissionState
  /** Whether the app can trigger the system prompt itself. */
  canRequest: boolean
  /** Whether a System Settings pane exists for it. */
  hasPane: boolean
  /** Extra text (e.g. probe result). */
  detail?: string
  /** True when granting needs a manual toggle in System Settings. */
  manual?: boolean
}
