// Shared IPC contract between the Electron main process and the renderer.
// Everything crossing the bridge must be structured-clone friendly (plain data).

export type PermissionMode = 'default' | 'acceptEdits' | 'bypassPermissions' | 'plan' | 'dontAsk' | 'auto'
export type EffortLevel = 'low' | 'medium' | 'high' | 'xhigh' | 'max'

/** Persisted metadata about a session managed by ClaudeGUI. */
export interface SessionRecord {
  /** Stable ClaudeGUI id (UUID). */
  id: string
  /** Claude Code session id (normally equal to `id`). */
  claudeSessionId: string
  title: string
  /** True while the title is auto-generated by Claude Code. */
  autoTitle?: boolean
  cwd: string
  model?: string
  permissionMode: PermissionMode
  effort?: EffortLevel
  createdAt: number
  lastActiveAt: number
  pinned?: boolean
  archived?: boolean
  source: 'gui' | 'cli-import'
  /** Set when a /clear produced a new conversation id inside the same process. */
  conversationId?: string
  /** Estimated USD cost accumulated across all processes of this session. */
  totalCostUsd?: number
}

export type SessionStatus = 'stopped' | 'starting' | 'idle' | 'running' | 'requires_action' | 'error'

export interface PendingPermission {
  requestId: string
  toolUseId: string
  toolName: string
  input: Record<string, unknown>
  suggestions?: unknown[]
  title?: string
  description?: string
  displayName?: string
  decisionReason?: string
  blockedPath?: string
  agentId?: string
  createdAt: number
}

export interface BackgroundTaskView {
  taskId: string
  taskType: string
  description: string
  ambient?: boolean
  status?: 'pending' | 'running' | 'completed' | 'failed' | 'killed' | 'paused' | 'stopped'
  toolUseId?: string
  summary?: string
  lastToolName?: string
  usage?: { total_tokens: number; tool_uses: number; duration_ms: number }
  startedAt?: number
}

export interface ActiveToolView {
  toolUseId: string
  toolName: string
  elapsedSeconds: number
  parentToolUseId: string | null
}

export interface TurnStats {
  costUsd: number
  durationMs: number
  numTurns: number
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
  cacheCreationTokens: number
  isError: boolean
  endedAt: number
}

export interface RateLimitView {
  status: 'allowed' | 'allowed_warning' | 'rejected'
  rateLimitType?: string
  utilization?: number
  resetsAt?: number
}

export interface SlashCommandView {
  name: string
  description: string
  argumentHint: string
  aliases?: string[]
}

export interface ModelInfoView {
  value: string
  displayName: string
  description: string
  supportedEffortLevels?: EffortLevel[]
}

export interface SessionLiveState {
  id: string
  status: SessionStatus
  processAlive: boolean
  model?: string
  permissionMode?: PermissionMode
  effort?: EffortLevel | null
  claudeVersion?: string
  cwd?: string
  activity?: 'compacting' | 'requesting' | null
  pendingPermissions: PendingPermission[]
  backgroundTasks: BackgroundTaskView[]
  activeTools: ActiveToolView[]
  lastTurn?: TurnStats
  totalCostUsd: number
  contextTokens?: number
  contextWindow?: number
  contextUsage?: ContextUsageView
  rateLimit?: RateLimitView
  unread: number
  lastActivityAt: number
  lastPreview?: string
  error?: string
  slashCommands?: SlashCommandView[]
  models?: ModelInfoView[]
  queuedCount: number
}

// ---------------------------------------------------------------------------
// Chat transcript model
// ---------------------------------------------------------------------------

export interface ImageAttachment {
  mediaType: string
  data: string // base64
  name?: string
}

export interface TextBlockView {
  type: 'text'
  text: string
}
export interface ThinkingBlockView {
  type: 'thinking'
  text: string
}
export interface ToolResultView {
  content: string
  images?: ImageAttachment[]
  isError: boolean
  structured?: unknown
  receivedAt: number
}
export interface ToolUseBlockView {
  type: 'tool_use'
  id: string
  name: string
  input: Record<string, unknown>
  /** Raw JSON accumulated while streaming; cleared once parsed. */
  partialJson?: string
  status: 'streaming' | 'pending' | 'running' | 'done' | 'error' | 'denied'
  startedAt: number
  result?: ToolResultView
  /** Messages produced inside a subagent started by this tool call. */
  children?: ChatMessage[]
  task?: {
    taskId: string
    description?: string
    subagentType?: string
    status?: BackgroundTaskView['status']
    summary?: string
    lastToolName?: string
    usage?: BackgroundTaskView['usage']
    isBackgrounded?: boolean
    outputFile?: string
  }
}
export type AssistantBlockView = TextBlockView | ThinkingBlockView | ToolUseBlockView

export interface UserChatMessage {
  kind: 'user'
  id: string
  ts: number
  text: string
  images?: ImageAttachment[]
  /** True for messages the CLI generated itself (task notifications, hook output, etc.). */
  synthetic?: boolean
  parentToolUseId: string | null
}
export interface AssistantChatMessage {
  kind: 'assistant'
  id: string
  ts: number
  model?: string
  blocks: AssistantBlockView[]
  streaming: boolean
  aborted?: boolean
  error?: string
  stopReason?: string | null
  parentToolUseId: string | null
  subagentType?: string
}
export interface SystemChatMessage {
  kind: 'system'
  id: string
  ts: number
  subtype: string
  level: 'info' | 'notice' | 'suggestion' | 'warning' | 'error'
  text: string
  data?: Record<string, unknown>
}
export interface ResultChatMessage {
  kind: 'result'
  id: string
  ts: number
  stats: TurnStats
  errorText?: string
}
export type ChatMessage = UserChatMessage | AssistantChatMessage | SystemChatMessage | ResultChatMessage

// ---------------------------------------------------------------------------
// Events main -> renderer
// ---------------------------------------------------------------------------

export type SessionEvent =
  | { type: 'state'; state: SessionLiveState }
  | { type: 'record'; record: SessionRecord }
  | { type: 'record-removed'; id: string }
  | { type: 'message'; sessionId: string; message: ChatMessage }
  | { type: 'messages-reset'; sessionId: string; messages: ChatMessage[] }
  | { type: 'message-removed'; sessionId: string; messageId: string }
  | { type: 'focus'; sessionId: string }

export interface PermissionDecision {
  behavior: 'allow' | 'deny'
  updatedInput?: Record<string, unknown>
  alwaysAllow?: boolean
  message?: string
  interrupt?: boolean
}

// ---------------------------------------------------------------------------
// Filesystem
// ---------------------------------------------------------------------------

export interface FsEntry {
  name: string
  path: string
  isDir: boolean
  isSymlink: boolean
  size: number
  mtime: number
  ext: string
}

export interface FileContent {
  path: string
  kind: 'text' | 'image' | 'binary' | 'too-large' | 'missing'
  text?: string
  base64?: string
  mimeType?: string
  size: number
  mtime: number
  language?: string
  truncated?: boolean
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

export type ThemeMode = 'system' | 'light' | 'dark'
export type AccentColor = 'system' | 'blue' | 'purple' | 'pink' | 'red' | 'orange' | 'yellow' | 'green' | 'graphite' | 'claude'
export type Density = 'comfortable' | 'compact'
export type ThinkingDisplay = 'collapsed' | 'expanded' | 'hidden'
export type DoubleClickAction = 'system' | 'editor' | 'viewer'
export type ResumeOnLaunch = 'none' | 'active' | 'pinned' | 'all'

export interface AppSettings {
  // ---- Claude
  /** Path to a claude binary; empty = SDK-bundled binary. */
  claudeExecutable: string
  defaultModel: string
  defaultPermissionMode: PermissionMode
  defaultEffort: EffortLevel | ''
  /** Extra KEY=VALUE lines applied to every Claude process (e.g. proxies). */
  extraEnv: string
  /** Maximum agent turns per message; 0 = unlimited. */
  maxTurns: number
  /** Maximum thinking tokens; 0 = model default. */
  maxThinkingTokens: number
  /** Tools that never prompt (comma or newline separated, e.g. "Read,Grep,Bash(git *)"). */
  allowedTools: string
  /** Tools Claude may not use at all. */
  disallowedTools: string
  useProjectSettings: boolean
  useLocalSettings: boolean
  /** Let Claude Code name new sessions automatically. */
  autoTitle: boolean

  // ---- General
  notifications: boolean
  notifyOnTurnFinished: boolean
  notifyOnPermission: boolean
  notifyOnError: boolean
  notificationSound: boolean
  dockBadge: boolean
  resumeOnLaunch: ResumeOnLaunch
  confirmQuit: boolean
  /** Pre-filled working directory for new sessions. */
  defaultCwd: string
  sendWithEnter: boolean
  recentDirectories: string[]

  // ---- Appearance
  theme: ThemeMode
  accent: AccentColor
  fontSize: number
  uiFont: string
  codeFont: string
  codeFontSize: number
  density: Density
  showTimestamps: boolean
  thinkingDisplay: ThinkingDisplay
  toolCardsExpanded: boolean
  chatMaxWidth: number
  groupSessionsByFolder: boolean
  translucentSidebar: boolean

  // ---- Files
  /** Command used for "open in editor"; supports {path} and {line} placeholders. */
  editorCommand: string
  showHiddenFiles: boolean
  /** Names hidden from the file tree (comma separated, e.g. node_modules,.git). */
  excludePatterns: string
  openBinaryWithSystemApp: boolean
  doubleClickAction: DoubleClickAction
  autoRevealEditedFiles: boolean
  maxPreviewKB: number
  showFileSizes: boolean

  // ---- Git
  gitEnabled: boolean
  gitShowStatusInTree: boolean
  gitAutoRefreshSeconds: number
  gitAutoFetchMinutes: number
  gitPushAfterCommit: boolean
  gitSignOff: boolean
  gitCommitTemplate: string

  // ---- Usage
  usageRefreshMinutes: number
  usageWarnPercent: number
  showUsageStatus: boolean
  showContextInSidebar: boolean
  showTaskCountsInSidebar: boolean

  // ---- Advanced
  toolResultMaxChars: number
  debugServer: boolean
  debugPort: number
}

export interface ThemeInfo {
  systemDark: boolean
  /** macOS accent colour as #rrggbb. */
  accent: string
}

// ---------------------------------------------------------------------------
// Plan usage limits (claude.ai rate-limit windows)
// ---------------------------------------------------------------------------

export type UsageSeverity = 'normal' | 'warning' | 'critical' | 'locked' | 'unknown'

export interface UsageWindow {
  key: string
  label: string
  group: 'session' | 'weekly' | 'model' | 'monthly' | 'other'
  /** 0-100, or null when the server did not report it. */
  percent: number | null
  severity: UsageSeverity
  /** Epoch ms when the window resets. */
  resetsAt?: number
  isActive?: boolean
  detail?: string
  /** Epoch ms of the last update for this window. */
  updatedAt: number
}

export interface UsageSnapshot {
  /** Epoch ms of the last explicit check (0 = never). */
  fetchedAt: number
  source: 'endpoint' | 'session' | 'event' | 'none'
  subscription?: string | null
  windows: UsageWindow[]
  error?: string
  nextCheckAt?: number
  checking?: boolean
}

// ---------------------------------------------------------------------------
// Context usage of a session
// ---------------------------------------------------------------------------

export interface ContextUsageView {
  totalTokens: number
  /** The window the percentage is measured against (auto-compact window). */
  maxTokens: number
  percentage: number
  model?: string
  categories: { name: string; tokens: number; kind?: string; color?: string }[]
  checkedAt: number
}

// ---------------------------------------------------------------------------
// Git
// ---------------------------------------------------------------------------

export type GitFileState = 'modified' | 'added' | 'deleted' | 'renamed' | 'copied' | 'typechange' | 'conflicted' | 'untracked' | 'ignored'

export interface GitFileStatus {
  /** Repo-relative path (directories end with '/'). */
  path: string
  absPath: string
  origPath?: string
  /** Staged (index) change. */
  index: GitFileState | null
  /** Unstaged (working tree) change. */
  worktree: GitFileState | null
  isDir: boolean
}

export interface GitRepoInfo {
  isRepo: boolean
  gitAvailable: boolean
  ghAvailable: boolean
  root?: string
  branch?: string
  detached?: boolean
  upstream?: string
  ahead?: number
  behind?: number
  remoteName?: string
  remoteUrl?: string
  remoteWebUrl?: string
  head?: { hash: string; subject: string; time: number }
  userName?: string
  userEmail?: string
  stashCount?: number
  hasCommits?: boolean
}

export interface GitStatusResult {
  info: GitRepoInfo
  files: GitFileStatus[]
  truncated?: boolean
  checkedAt: number
}

export interface GitCommitInfo {
  hash: string
  shortHash: string
  subject: string
  author: string
  time: number
  refs?: string
}

export interface GitDiffResult {
  path: string
  before: string
  after: string
  beforeLabel: string
  afterLabel: string
  binary: boolean
  tooLarge?: boolean
}

export interface GitBranchInfo {
  name: string
  current: boolean
  upstream?: string
}

export interface FileProbe {
  kind: 'text' | 'image' | 'binary' | 'too-large' | 'missing' | 'dir' | 'bundle'
  size: number
  ext: string
}

export interface CliSessionSummary {
  sessionId: string
  summary: string
  lastModified: number
  createdAt?: number
  cwd?: string
  firstPrompt?: string
  customTitle?: string
  fileSize?: number
  gitBranch?: string
  alreadyImported: boolean
}

export interface AppInfo {
  version: string
  platform: string
  electron: string
  node: string
  sdkVersion: string
  userDataPath: string
  claudeExecutable: string
  homeDir: string
}
